"""
Constants for the mappedcover integration.
"""

DOMAIN = "mappedcover"

DEFAULT_LABEL = "Covers"

DEFAULT_RENAME_PATTERN = "^.*$"
DEFAULT_RENAME_REPLACEMENT = "Mapped \\g<0>"
DEFAULT_MIN_POSITION = 0
DEFAULT_MAX_POSITION = 100
DEFAULT_MIN_TILT_POSITION = 0
DEFAULT_MAX_TILT_POSITION = 100
DEFAULT_CLOSE_TILT_IF_DOWN = True
DEFAULT_THROTTLE = 100
